# Generated by Django 3.2.4 on 2021-07-16 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atendidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Anio', models.IntegerField()),
                ('NroMes', models.IntegerField()),
                ('Ubigeo', models.IntegerField()),
                ('Departamento', models.CharField(max_length=30)),
                ('Provincia', models.CharField(max_length=30)),
                ('Distrito', models.CharField(max_length=30)),
                ('Sexo', models.CharField(max_length=3)),
                ('Etapa', models.CharField(max_length=30)),
                ('Diagnostico', models.CharField(max_length=30)),
                ('Atendidos', models.IntegerField()),
                ('Atenciones', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tamizajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Anio', models.IntegerField()),
                ('NroMes', models.IntegerField()),
                ('Ubigeo', models.IntegerField()),
                ('Departamento', models.CharField(max_length=29)),
                ('Provincia', models.CharField(max_length=30)),
                ('Distrito', models.CharField(max_length=30)),
                ('Sexo', models.CharField(max_length=3)),
                ('Etapa', models.CharField(max_length=30)),
                ('GrupoTamizaje', models.CharField(max_length=30)),
                ('DetalleTamizaje', models.CharField(max_length=30)),
                ('Casos', models.IntegerField()),
            ],
        ),
    ]
