# Generated by Django 3.2.4 on 2021-07-21 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trastornos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('fuente', models.CharField(max_length=110, verbose_name='Fuente')),
                ('descripcion', models.CharField(max_length=110, verbose_name='Descripcion')),
                ('imagen', models.URLField(max_length=255)),
            ],
        ),
    ]
