# Generated by Django 3.2.4 on 2021-07-21 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trastornos', '0002_noticia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(max_length=150, verbose_name='Titulo'),
        ),
    ]
